// ICAO Q-Code Decoder - Full reference for all subject and condition codes

export interface QCodeParts {
  qCode: string; // Full 5-letter code (e.g., QMRXX)
  subjectCode: string; // 2nd & 3rd letter (e.g., MR)
  conditionCode: string; // 4th & 5th letter (e.g., XX)
  subjectDescription: string;
  conditionDescription: string;
}

// Subject codes (2nd & 3rd letters)
const SUBJECT_CODES: Record<string, string> = {
  AA: 'Airspace - Minimum altitude',
  AB: 'Airspace - Maximum altitude',
  AC: 'Airspace - Class designation',
  AD: 'Airspace - Designation',
  AE: 'Airspace - Activation',
  AF: 'Airspace - Affected area',
  AO: 'Airspace - Organization',
  CA: 'Communications - Aeronautical fixed service',
  CB: 'Communications - ADS-B',
  CC: 'Communications - Communication facility',
  CD: 'Communications - Displacement',
  CE: 'Communications - Emergency frequency',
  FA: 'Facility - Aerodrome',
  FB: 'Facility - Aerodrome beacon',
  FC: 'Facility - Flight information center',
  FD: 'Facility - Docking',
  FE: 'Facility - Emergency equipment',
  FF: 'Facility - Fire fighting',
  FG: 'Facility - Ground control',
  FH: 'Facility - Apron/holding',
  FI: 'Facility - Runway/taxiway intersection',
  FJ: 'Facility - Fuel',
  FK: 'Facility - Aircraft parking',
  FM: 'Facility - Maintenance',
  FN: 'Facility - Noise',
  FO: 'Facility - Operational',
  FP: 'Facility - Personnel',
  FQ: 'Facility - Quadrant/sector',
  FR: 'Facility - Runway',
  FS: 'Facility - Shoulder/verge',
  FT: 'Facility - Threshold',
  FU: 'Facility - Unmarked',
  FV: 'Facility - Visual aids',
  FW: 'Facility - Weather',
  LA: 'Lighting - Approach lights',
  LB: 'Lighting - Aerodrome beacon',
  LC: 'Lighting - Ceiling light',
  LD: 'Lighting - Downwind light',
  LE: 'Lighting - Elevated light',
  LF: 'Lighting - Flare path',
  LG: 'Lighting - Glide path light',
  LH: 'Lighting - High intensity',
  LI: 'Lighting - Identification light',
  LJ: 'Lighting - Judge light',
  LK: 'Lighting - Kinetic light',
  LL: 'Lighting - Low intensity',
  LM: 'Lighting - Medium intensity',
  LN: 'Lighting - Narrow beam',
  LO: 'Lighting - Omnidirectional',
  LP: 'Lighting - Parking area',
  LR: 'Lighting - Runway light',
  LS: 'Lighting - Stop bar light',
  LT: 'Lighting - Taxiway light',
  MA: 'Movement - Apron',
  MB: 'Movement - Holding',
  MC: 'Movement - Movement area',
  MD: 'Movement - Displacement',
  ME: 'Movement - Elevation',
  MF: 'Movement - Friction',
  MG: 'Movement - Gradient',
  MH: 'Movement - Holding point',
  MI: 'Movement - Intersection',
  MJ: 'Movement - Crossing',
  MM: 'Movement - Main landing area',
  MN: 'Movement - Non-precision approach',
  MO: 'Movement - Obstacle',
  MP: 'Movement - Parking',
  MQ: 'Movement - Quadrant',
  MR: 'Movement - Runway',
  MS: 'Movement - Shoulder',
  MT: 'Movement - Threshold',
  MU: 'Movement - Unmarked',
  MV: 'Movement - Visual aids',
  MW: 'Movement - Work in progress',
  NA: 'Navigation - NDB',
  NB: 'Navigation - DME',
  NC: 'Navigation - Fan marker',
  ND: 'Navigation - Locator',
  NE: 'Navigation - Middle marker',
  NF: 'Navigation - Outer marker',
  NG: 'Navigation - Glide path',
  NH: 'Navigation - High frequency',
  NI: 'Navigation - Homing',
  NK: 'Navigation - Marker',
  NL: 'Navigation - Localizer',
  NM: 'Navigation - Compass locator',
  NN: 'Navigation - Navigation facility',
  NO: 'Navigation - Omnidirectional',
  NP: 'Navigation - Positioning',
  NR: 'Navigation - Reporting',
  NS: 'Navigation - Speed',
  NT: 'Navigation - Terminal',
  NV: 'Navigation - VOR',
  OB: 'Obstacle - Obstacle',
  OE: 'Obstacle - Elevations',
  OF: 'Obstacle - Fairway hazard',
  OG: 'Obstacle - Ground hazard',
  OH: 'Obstacle - High altitude',
  OM: 'Obstacle - Marked',
  ON: 'Obstacle - Navigation',
  OP: 'Obstacle - Pipeline',
  OR: 'Obstacle - Removed',
  OS: 'Obstacle - Supported',
  OT: 'Obstacle - Tower',
  OW: 'Obstacle - Wind farm',
  PA: 'Procedure - Standard arrival route',
  PB: 'Procedure - Holding',
  PC: 'Procedure - Crossing',
  PD: 'Procedure - Descent',
  PE: 'Procedure - Established',
  PF: 'Procedure - Final approach',
  PG: 'Procedure - Gradient',
  PH: 'Procedure - Holding procedure',
  PI: 'Procedure - Initial approach',
  PJ: 'Procedure - Climb',
  PK: 'Procedure - Procedure',
  PL: 'Procedure - Level',
  PM: 'Procedure - Procedure modification',
  PN: 'Procedure - Procedure new',
  PO: 'Procedure - Procedure operating',
  PP: 'Procedure - Procedure preparation',
  PR: 'Procedure - Procedure route',
  PS: 'Procedure - Standard departure',
  PT: 'Procedure - Transition',
  RA: 'Restriction - Alert area',
  RD: 'Restriction - Danger area',
  RM: 'Restriction - Military area',
  RP: 'Restriction - Prohibited area',
  RR: 'Restriction - Restricted area',
  RZ: 'Restriction - Restricted zone',
};

// Condition codes (4th & 5th letters)
const CONDITION_CODES: Record<string, string> = {
  AC: 'Withdrawn maintenance',
  AO: 'Operational',
  AS: 'Unserviceable',
  CA: 'Activated',
  CB: 'Changed braking action',
  CC: 'Changed course',
  CF: 'Changed frequency',
  CN: 'Canceled',
  CO: 'Changed operating schedule',
  CR: 'Changed runway',
  CU: 'Changed upper limit',
  HA: 'Braking action poor/medium',
  HB: 'Braking action poor',
  HC: 'Braking action medium',
  HD: 'Density altitude',
  HE: 'Humidity/temperature',
  HI: 'Covered by ice',
  HJ: 'Jet blast',
  HL: 'Low level wind shear',
  HO: 'Obscured',
  HP: 'Snow clearance in progress',
  HR: 'Reduced operations',
  HS: 'Surface condition',
  HT: 'Taxiing',
  HU: 'Unserviceable',
  HV: 'Volcanic ash',
  HW: 'Weather',
  HX: 'Water on runway',
  LC: 'Closed',
  LD: 'Unsafe',
  LI: 'Closed IFR',
  LO: 'Operational limited',
  LU: 'Unserviceable',
  PP: 'Partially prepared',
  XX: 'Encoded in plain language (no standardized code)',
};

export function decodeQCode(qCode: string): QCodeParts {
  const cleaned = qCode.toUpperCase().trim();

  // Expect format: QXXXXX (5 letters starting with Q)
  if (!cleaned.match(/^Q[A-Z]{4}$/)) {
    return {
      qCode: cleaned,
      subjectCode: '',
      conditionCode: '',
      subjectDescription: 'Invalid Q-code format',
      conditionDescription: '',
    };
  }

  const subjectCode = cleaned.substring(1, 3); // 2nd & 3rd letters
  const conditionCode = cleaned.substring(3, 5); // 4th & 5th letters

  return {
    qCode: cleaned,
    subjectCode,
    conditionCode,
    subjectDescription: SUBJECT_CODES[subjectCode] || `Unknown subject code: ${subjectCode}`,
    conditionDescription: CONDITION_CODES[conditionCode] || `Unknown condition code: ${conditionCode}`,
  };
}

export function formatQCodeExplanation(qCode: string): string {
  const decoded = decodeQCode(qCode);
  return `${decoded.subjectDescription} - ${decoded.conditionDescription}`;
}
